
x-var:
  - &POSTGRES_USER
    postgres
  - &POSTGRES_PASSWORD
    default
  - &POSTGRES_DATABASE
    spar
  - &POSTGRES_HOST
    postgres
  - &POSTGRES_PORT
    5432
  - &POSTGRES_SCHEMA
    spar
  - &POSTGRES_FLYWAY_URL_POSTGRES
    jdbc:postgresql://postgres:5432/spar
  - &SOURCE_DATA_FOLDER
    /app/data
  - &DATA_CLASSIFICATION_SS
    /app/data_classification.xlsx
  - &ORACLE_USER
    THE
  - &ORACLE_PASSWORD
    default
  - &ORACLE_DATABASE
    DBDOCK_01
  - &ORACLE_HOST
    oracle-spar
  - &ORACLE_PORT
    1521
  - &ORACLE_FLYWAY_URL
    jdbc:oracle:thin:@//oracle-spar:1521/DBDOCK_01



x-postgres-vars: &postgres-vars
  POSTGRES_DB: *POSTGRES_DATABASE
  POSTGRES_HOST: *POSTGRES_HOST
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_PORT: *POSTGRES_PORT
  FLYWAY_URL_POSTGRES: *POSTGRES_FLYWAY_URL_POSTGRES

  POSTGRES_HOST_LOCAL: *POSTGRES_HOST
  POSTGRES_PORT_LOCAL: *POSTGRES_PORT
  POSTGRES_SERVICE_LOCAL: *POSTGRES_DATABASE
  POSTGRES_USER_LOCAL: *POSTGRES_USER
  POSTGRES_PASSWORD_LOCAL: *POSTGRES_PASSWORD
  POSTGRES_SCHEMA_TO_SYNC_LOCAL: *POSTGRES_SCHEMA
  LOCAL_DATA_DIR: *SOURCE_DATA_FOLDER


x-oracle-vars: &oracle-vars
  # Used by the Oracle container in the setup
  ORACLE_DATABASE: *ORACLE_DATABASE
  ORACLE_PASSWORD: *ORACLE_PASSWORD
  ORACLE_HOST: *ORACLE_HOST
  APP_USER: *ORACLE_USER
  APP_USER_PASSWORD: *ORACLE_PASSWORD
  # used by the sync process
  ORACLE_SYNC_PASSWORD: *ORACLE_PASSWORD
  ORACLE_SYNC_USER: *ORACLE_USER
  FLYWAY_URL: *ORACLE_FLYWAY_URL
  # data load process
  LOCAL_DATA_DIR: *SOURCE_DATA_FOLDER
  DATA_CLASSIFICATION_SS: *DATA_CLASSIFICATION_SS
  # used by the data load process
  ORACLE_HOST_LOCAL: *ORACLE_HOST
  ORACLE_PORT_LOCAL: *ORACLE_PORT
  ORACLE_SERVICE_LOCAL: *ORACLE_DATABASE
  ORACLE_USER_LOCAL: *ORACLE_USER
  ORACLE_PASSWORD_LOCAL: *ORACLE_PASSWORD
  ORACLE_SCHEMA_TO_SYNC_LOCAL: *ORACLE_USER

services:
  # dbutils:
  #   image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
  #   container_name: dbutils


  postgres:
    #image: postgis/postgis:15-master
    image: postgis/postgis:17-3.5-alpine
    container_name: postgres
    environment:
      <<: *postgres-vars
    volumes:
      # - ./migrations_spar/init.sql:/initdb/init.sql
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", postgres]
    ports: ["5432:5432"]

  postgres-getmigrations:
    image: alpine:3.21
    container_name: postgres-getmigrations
    volumes:
      - "postgres-migrations-volume:/flyway"
      - "./getmigrations.sh:/getmigrations.sh"
    command: sh ./getmigrations.sh
    # command: sleep 10000
    depends_on:
        postgres:
          condition: service_healthy

  # used to verify that the get migrations worked
  postgres-getmig-test:
    image: alpine:3.21
    container_name: postgres-getmig-test
    volumes:
      - "postgres-migrations-volume:/flyway:ro"
      - "./getmigrations.sh:/getmigrations.sh"
    command: sleep 10000
    depends_on:
        postgres-getmigrations:
          condition: service_completed_successfully

  postgres-migrations:
    image: flyway/flyway:10-alpine
    container_name: postgres-migrations
    command: info migrate info
    volumes:
      # this is the migrations from spar... the one to use moving forward
      - "postgres-migrations-volume:/flyway:ro"
      #- "./migrations_spar/sql:/flyway/sql:ro"
    environment:
      <<: [*postgres-vars]
      FLYWAY_URL: *POSTGRES_FLYWAY_URL_POSTGRES
      FLYWAY_USER: *POSTGRES_USER
      FLYWAY_PASSWORD: *POSTGRES_PASSWORD
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_DEFAULT_SCHEMA: *POSTGRES_SCHEMA
    depends_on:
      postgres-getmigrations:
        condition: service_completed_successfully

  # data-load here doesn't work references non existing shell script
  postgres-data-load:
    image: nr-fds-pyetl-oracle-data-load:latest
    build:
        context: ./  # Path to the directory containing the Dockerfile
        dockerfile: Dockerfile.dbutils  # Name of the Dockerfile (optional if named "Dockerfile")
    # image: python:3.13-slim-bookworm
    container_name: postgres-data-load
    working_dir: /app
    #entrypoint: ["python", "db_env_utils/main_ingest.py", OC_POSTGRES, TEST]
    entrypoint: ["bash", "/app/run_data_inject_oc.sh"]

    volumes:
      - "./docker-compose.yml:/app/docker-compose.yml"
      #- "./ora-env/data/docker:/app/data"
      - "oracle-data-load:/app/data"

    environment:
      <<: [*postgres-vars]
    env_file:
      - ".env"
    depends_on:
      postgres-migrations:
        condition: service_completed_successfully

  # Name of the Docker Compose service
  oracle-spar:
    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-free:latest
    # Forward Oracle port to localhost
    container_name: oracle-spar
    ports:
      - "1521:1521"
    # Provide passwords and other environment variables to the container
    environment:
      <<: *oracle-vars
    # Customize healthcheck script options for startup
    healthcheck:
      test: ["CMD", "/opt/oracle/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
    # Mount a local SQL file to initialize your schema at startup
    volumes:
      - oracle-data:/opt/oracle/oradata  # Mount the volume to the Oracle data directory
      - ./data_prep/ora_db_init/db_init/db_init.sql:/container-entrypoint-initdb.d/my-init.sql:ro

  oracle-migrations:
    image: flyway/flyway:10-alpine
    container_name: oracle-migrations
    command: info migrate info
    volumes:
      - "./ora-env/migrations/ora:/flyway/sql:ro"
    environment:
      <<: *oracle-vars
      FLYWAY_USER: *ORACLE_USER
      FLYWAY_PASSWORD: *ORACLE_PASSWORD
      FLYWAY_DEFAULT_SCHEMA: *ORACLE_USER
      FLYWAY_BASELINE_ON_MIGRATE: true
    depends_on:
      oracle-spar:
        condition: service_healthy

  # doesnt work, references non existing shell script
  oracle-data-load:
    image: nr-fds-pyetl-oracle-data-load:latest
    user: "0:0"
    build:
        context: ./  # Path to the directory containing the Dockerfile
        dockerfile: Dockerfile.dbutils  # Name of the Dockerfile (optional if named "Dockerfile")
    # image: python:3.13-slim-bookworm
    container_name: oracle-data-load
    # "CMD",
    # entrypoint: [ "/application/docker_run_ORA_TEST.sh"]
    working_dir: /app
    # entrypoint: ["python", "db_env_utils/main_ingest.py", ORA, PROD]
    entrypoint: ["bash", "/app/run_data_inject_ora.sh"]
    volumes:
      - "oracle-data-load:/app/data"
      - "./ora-env/data/temp/data_classification.xlsx:/app/data_classification.xlsx"
    env_file:
      - ".env"
    environment:
      <<: [*oracle-vars]

    depends_on:
      oracle-migrations:
        condition: service_completed_successfully

  # debug service, useful for understanding how environment variables work
  etl-env-setup:
    container_name: etl-env-setup
    image: functions/alpine:health
    command: ["/bin/sh", "-c", "echo Postgres and Oracle envs now live!"]
    depends_on:
      oracle-data-load:
        condition: service_completed_successfully
      postgres-data-load:
        condition: service_completed_successfully

  sync:
    container_name: sync
    build:
      context: sync
      dockerfile: Dockerfile
    environment:
      <<: [*postgres-vars, *oracle-vars]
      TEST_MODE: false
      EXECUTION_ID: 9999
      ORACLE_PORT: *ORACLE_PORT
      ORACLE_SERVICE: *ORACLE_DATABASE
      ORA_NON_ENRCYPT_LISTENER: True
    command: ["python", "/app/src/main.py"]
    # command: ["sleep", "10000"]
    volumes:
    - "./sync/src:/app/src"
    - "./sync/uv.lock:/application/uv.lock"
    - "./sync/pyproject.toml:/application/pyproject.toml"
    depends_on:
      etl-env-setup:
        condition: service_completed_successfully



  cloudbeaver:
    profiles: ["cloudbeaver"]
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: always
    ports:
      - '8978:8978'
    volumes:
      - /opt/cloudbeaver/workspace
    depends_on:
      etl:
        condition: service_completed_successfully

  # # debug service, useful for understanding how environment variables work
  # echoit:
  #   image: functions/alpine:health
  #   environment:
  #     <<: *oracle-vars
  #     FLYWAY_USER: "${APP_USER}"
  #     FLYWAY_PASSWORD: "${APP_USER_PASSWORD}"
  #     FLYWAY_BASELINE_ON_MIGRATE: true
  #     FLYWAY_DEFAULT_SCHEMA: "${APP_USER}"
  #   entrypoint: ["/bin/sh", "-c", "export && echo \"oradb is ${FLYWAY_USER}\" &&  exec $fprocess"]

volumes:
  oracle-data:
  postgres-migrations-volume:
  oracle-data-load:
