
  CREATE TABLE "THE"."NAD_DATUM_CODE" 
   (	"NAD_DATUM_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."NAD_DATUM_CODE_PK" ON "THE"."NAD_DATUM_CODE" ("NAD_DATUM_CODE") 
  ;
ALTER TABLE "THE"."NAD_DATUM_CODE" ADD CONSTRAINT "NAD_DATUM_CODE_PK" PRIMARY KEY ("NAD_DATUM_CODE")
  USING INDEX "THE"."NAD_DATUM_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."SEEDLOT_SOURCE_CODE" 
   (	"SEEDLOT_SOURCE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "SSCD_PK" PRIMARY KEY ("SEEDLOT_SOURCE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."ORCHARD" 
   (	"ORCHARD_ID" VARCHAR2(3) NOT NULL ENABLE, 
	"ORCHARD_LOT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"GENERATION_NUMBER" NUMBER(3,2), 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ORCHARD_NAME" VARCHAR2(30), 
	"ORCHARD_STAGE_CODE" VARCHAR2(3), 
	"LICENSED_IND" VARCHAR2(1), 
	"LICENSED_DATE" DATE, 
	"LICENSE_RENEWAL_DATE" DATE, 
	"VEGETATION_CODE" VARCHAR2(8), 
	"BEC_ZONE" VARCHAR2(4), 
	"BEC_SUBZONE" VARCHAR2(3), 
	"VARIANT" VARCHAR2(1), 
	"BEC_VERSION_ID" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "THE"."ORCHARD_PK" ON "THE"."ORCHARD" ("ORCHARD_ID") 
  ;
ALTER TABLE "THE"."ORCHARD" ADD CONSTRAINT "ORCHARD_PK" PRIMARY KEY ("ORCHARD_ID")
  USING INDEX "THE"."ORCHARD_PK"  ENABLE;

  CREATE TABLE "THE"."COLLECTION_SOURCE_CODE" 
   (	"COLLECTION_SOURCE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."COLLECTION_SOURCE_CODE_PK" ON "THE"."COLLECTION_SOURCE_CODE" ("COLLECTION_SOURCE_CODE") 
  ;
ALTER TABLE "THE"."COLLECTION_SOURCE_CODE" ADD CONSTRAINT "COLLECTION_SOURCE_CODE_PK" PRIMARY KEY ("COLLECTION_SOURCE_CODE")
  USING INDEX "THE"."COLLECTION_SOURCE_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."CONE_COLLECTION_METHOD_CODE" 
   (	"CONE_COLLECTION_METHOD_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."CONE_COLLECTION_METHOD_CODE_PK" ON "THE"."CONE_COLLECTION_METHOD_CODE" ("CONE_COLLECTION_METHOD_CODE") 
  ;
ALTER TABLE "THE"."CONE_COLLECTION_METHOD_CODE" ADD CONSTRAINT "CONE_COLLECTION_METHOD_CODE_PK" PRIMARY KEY ("CONE_COLLECTION_METHOD_CODE")
  USING INDEX "THE"."CONE_COLLECTION_METHOD_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."VEGETATION_CODE" 
   (	"VEGETATION_CODE" VARCHAR2(8) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."VEGETATION_CODE_PK" ON "THE"."VEGETATION_CODE" ("VEGETATION_CODE") 
  ;
ALTER TABLE "THE"."VEGETATION_CODE" ADD CONSTRAINT "VEGETATION_CODE_PK" PRIMARY KEY ("VEGETATION_CODE")
  USING INDEX "THE"."VEGETATION_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."NMBR_TREES_FROM_CODE" 
   (	"NMBR_TREES_FROM_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."NMBR_TREES_FROM_CODE_PK" ON "THE"."NMBR_TREES_FROM_CODE" ("NMBR_TREES_FROM_CODE") 
  ;
ALTER TABLE "THE"."NMBR_TREES_FROM_CODE" ADD CONSTRAINT "NMBR_TREES_FROM_CODE_PK" PRIMARY KEY ("NMBR_TREES_FROM_CODE")
  USING INDEX "THE"."NMBR_TREES_FROM_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."CLIENT_ID_TYPE_CODE" 
   (	"CLIENT_ID_TYPE_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CITC_PK" PRIMARY KEY ("CLIENT_ID_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."REGISTRY_COMPANY_TYPE_CODE" 
   (	"REGISTRY_COMPANY_TYPE_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CRCTC_PK" PRIMARY KEY ("REGISTRY_COMPANY_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_TYPE_CODE" 
   (	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CTCD_PK" PRIMARY KEY ("CLIENT_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_TYPE_COMPANY_XREF" 
   (	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"REGISTRY_COMPANY_TYPE_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CTCX_PK" PRIMARY KEY ("CLIENT_TYPE_CODE", "REGISTRY_COMPANY_TYPE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CTCX_CTC_FK" FOREIGN KEY ("CLIENT_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_TYPE_CODE" ("CLIENT_TYPE_CODE") ENABLE, 
	 CONSTRAINT "CTCX_CRCTC_FK" FOREIGN KEY ("REGISTRY_COMPANY_TYPE_CODE")
	  REFERENCES "THE"."REGISTRY_COMPANY_TYPE_CODE" ("REGISTRY_COMPANY_TYPE_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_STATUS_CODE" 
   (	"CLIENT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."CSTC_PK" ON "THE"."CLIENT_STATUS_CODE" ("CLIENT_STATUS_CODE") 
  ;
ALTER TABLE "THE"."CLIENT_STATUS_CODE" ADD CONSTRAINT "CSTC_PK" PRIMARY KEY ("CLIENT_STATUS_CODE")
  USING INDEX "THE"."CSTC_PK"  ENABLE;

  CREATE TABLE "THE"."ORG_UNIT" 
   (	"ORG_UNIT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ORG_UNIT_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"ORG_UNIT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"LOCATION_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"AREA_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"TELEPHONE_NO" VARCHAR2(7) NOT NULL ENABLE, 
	"ORG_LEVEL_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"OFFICE_NAME_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"ROLLUP_REGION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLLUP_REGION_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"ROLLUP_DIST_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLLUP_DIST_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE
   ) ;
  CREATE UNIQUE INDEX "THE"."I1$_ORG_UNIT" ON "THE"."ORG_UNIT" ("ORG_UNIT_NO") 
  ;
ALTER TABLE "THE"."ORG_UNIT" ADD CONSTRAINT "ORG_UNIT_PK" PRIMARY KEY ("ORG_UNIT_NO")
  USING INDEX "THE"."I1$_ORG_UNIT"  ENABLE;

   CREATE SEQUENCE  "THE"."FOREST_CLIENT_AUDIT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 515452 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE TABLE "THE"."FOREST_CLIENT" 
   (	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"LEGAL_FIRST_NAME" VARCHAR2(30), 
	"LEGAL_MIDDLE_NAME" VARCHAR2(30), 
	"CLIENT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"BIRTHDATE" DATE, 
	"CLIENT_ID_TYPE_CODE" VARCHAR2(4), 
	"CLIENT_IDENTIFICATION" VARCHAR2(40), 
	"REGISTRY_COMPANY_TYPE_CODE" VARCHAR2(4), 
	"CORP_REGN_NMBR" VARCHAR2(9), 
	"CLIENT_ACRONYM" VARCHAR2(8), 
	"WCB_FIRM_NUMBER" VARCHAR2(6), 
	"OCG_SUPPLIER_NMBR" VARCHAR2(10), 
	"CLIENT_COMMENT" VARCHAR2(4000), 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "FOREST_CLIENT_PK" PRIMARY KEY ("CLIENT_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FC_OU_FK" FOREIGN KEY ("ADD_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "FC_CITC_FK" FOREIGN KEY ("CLIENT_ID_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_ID_TYPE_CODE" ("CLIENT_ID_TYPE_CODE") ENABLE, 
	 CONSTRAINT "FC_CSC_FK" FOREIGN KEY ("CLIENT_STATUS_CODE")
	  REFERENCES "THE"."CLIENT_STATUS_CODE" ("CLIENT_STATUS_CODE") ENABLE, 
	 CONSTRAINT "FC_CTCX_FK" FOREIGN KEY ("CLIENT_TYPE_CODE", "REGISTRY_COMPANY_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_TYPE_COMPANY_XREF" ("CLIENT_TYPE_CODE", "REGISTRY_COMPANY_TYPE_CODE") ENABLE, 
	 CONSTRAINT "FC_OU_IS_UPDATED_BY_FK" FOREIGN KEY ("UPDATE_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE
   ) ;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "THE"."V_CLIENT_PUBLIC" ("CLIENT_NUMBER", "CLIENT_NAME", "LEGAL_FIRST_NAME", "LEGAL_MIDDLE_NAME", "CLIENT_STATUS_CODE", "CLIENT_TYPE_CODE") AS 
  SELECT client_number
       , client_name
       , legal_first_name
       , legal_middle_name
       , client_status_code
       , client_type_code
    FROM forest_client;

   CREATE SEQUENCE  "THE"."CLIENT_UPDATE_REASON_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 24381 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE TABLE "THE"."CLIENT_UPDATE_ACTION_CODE" 
   (	"CLIENT_UPDATE_ACTION_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CUAC_PK" PRIMARY KEY ("CLIENT_UPDATE_ACTION_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_UPDATE_REASON_CODE" 
   (	"CLIENT_UPDATE_REASON_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CURCD_PK" PRIMARY KEY ("CLIENT_UPDATE_REASON_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_ACTION_REASON_XREF" 
   (	"CLIENT_UPDATE_ACTION_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"CLIENT_UPDATE_REASON_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "CARX_PK" PRIMARY KEY ("CLIENT_UPDATE_ACTION_CODE", "CLIENT_UPDATE_REASON_CODE", "CLIENT_TYPE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CARX_CTC_FK" FOREIGN KEY ("CLIENT_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_TYPE_CODE" ("CLIENT_TYPE_CODE") ENABLE, 
	 CONSTRAINT "CARX_CUAC_FK" FOREIGN KEY ("CLIENT_UPDATE_ACTION_CODE")
	  REFERENCES "THE"."CLIENT_UPDATE_ACTION_CODE" ("CLIENT_UPDATE_ACTION_CODE") ENABLE, 
	 CONSTRAINT "CARX_CURC_FK" FOREIGN KEY ("CLIENT_UPDATE_REASON_CODE")
	  REFERENCES "THE"."CLIENT_UPDATE_REASON_CODE" ("CLIENT_UPDATE_REASON_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_AUDIT_CODE" 
   (	"CLIENT_AUDIT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CAUDC_PK" PRIMARY KEY ("CLIENT_AUDIT_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."FOR_CLI_AUDIT" 
   (	"FOREST_CLIENT_AUDIT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"CLIENT_AUDIT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"LEGAL_FIRST_NAME" VARCHAR2(30), 
	"LEGAL_MIDDLE_NAME" VARCHAR2(30), 
	"CLIENT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"BIRTHDATE" DATE, 
	"CLIENT_ID_TYPE_CODE" VARCHAR2(4), 
	"CLIENT_IDENTIFICATION" VARCHAR2(40), 
	"REGISTRY_COMPANY_TYPE_CODE" VARCHAR2(4), 
	"CORP_REGN_NMBR" VARCHAR2(9), 
	"CLIENT_ACRONYM" VARCHAR2(8), 
	"WCB_FIRM_NUMBER" VARCHAR2(6), 
	"OCG_SUPPLIER_NMBR" VARCHAR2(10), 
	"CLIENT_COMMENT" VARCHAR2(4000), 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "FCAUD_PK" PRIMARY KEY ("FOREST_CLIENT_AUDIT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FCA_OU_FK" FOREIGN KEY ("ADD_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "FCA_FC_FK" FOREIGN KEY ("CLIENT_NUMBER")
	  REFERENCES "THE"."FOREST_CLIENT" ("CLIENT_NUMBER") ENABLE, 
	 CONSTRAINT "FCA_CAUDC_FK" FOREIGN KEY ("CLIENT_AUDIT_CODE")
	  REFERENCES "THE"."CLIENT_AUDIT_CODE" ("CLIENT_AUDIT_CODE") ENABLE, 
	 CONSTRAINT "FCA_OU_IS_UPDATED_BY_FK" FOREIGN KEY ("UPDATE_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_UPDATE_REASON" 
   (	"CLIENT_UPDATE_REASON_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"CLIENT_UPDATE_ACTION_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"CLIENT_UPDATE_REASON_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"FOREST_CLIENT_AUDIT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "CU_PK" PRIMARY KEY ("CLIENT_UPDATE_REASON_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CU_FCA_FK" FOREIGN KEY ("FOREST_CLIENT_AUDIT_ID")
	  REFERENCES "THE"."FOR_CLI_AUDIT" ("FOREST_CLIENT_AUDIT_ID") ENABLE, 
	 CONSTRAINT "CU_CARX_FK" FOREIGN KEY ("CLIENT_UPDATE_ACTION_CODE", "CLIENT_UPDATE_REASON_CODE", "CLIENT_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_ACTION_REASON_XREF" ("CLIENT_UPDATE_ACTION_CODE", "CLIENT_UPDATE_REASON_CODE", "CLIENT_TYPE_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_LOCATION" 
   (	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"CLIENT_LOCN_NAME" VARCHAR2(40), 
	"HDBS_COMPANY_CODE" VARCHAR2(5), 
	"ADDRESS_1" VARCHAR2(40) NOT NULL ENABLE, 
	"ADDRESS_2" VARCHAR2(40), 
	"ADDRESS_3" VARCHAR2(40), 
	"CITY" VARCHAR2(30) NOT NULL ENABLE, 
	"PROVINCE" VARCHAR2(50), 
	"POSTAL_CODE" VARCHAR2(10), 
	"COUNTRY" VARCHAR2(50) NOT NULL ENABLE, 
	"BUSINESS_PHONE" VARCHAR2(10), 
	"HOME_PHONE" VARCHAR2(10), 
	"CELL_PHONE" VARCHAR2(10), 
	"FAX_NUMBER" VARCHAR2(10), 
	"EMAIL_ADDRESS" VARCHAR2(128), 
	"LOCN_EXPIRED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"RETURNED_MAIL_DATE" DATE, 
	"TRUST_LOCATION_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"CLI_LOCN_COMMENT" VARCHAR2(4000), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "CLIENT_LOCATION_PK" PRIMARY KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CL_FC_FK" FOREIGN KEY ("CLIENT_NUMBER")
	  REFERENCES "THE"."FOREST_CLIENT" ("CLIENT_NUMBER") ENABLE, 
	 CONSTRAINT "CL_OU_FK" FOREIGN KEY ("UPDATE_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "CL_OU_IS_CREATED_BY_FK" FOREIGN KEY ("ADD_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_RELATIONSHIP_CODE" 
   (	"CLIENT_RELATIONSHIP_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "RELCD_PK" PRIMARY KEY ("CLIENT_RELATIONSHIP_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_RELATIONSHIP_TYPE_XREF" 
   (	"CLIENT_RELATIONSHIP_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"PRIMARY_CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"SECONDARY_CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CRX_PK" PRIMARY KEY ("CLIENT_RELATIONSHIP_CODE", "SECONDARY_CLIENT_TYPE_CODE", "PRIMARY_CLIENT_TYPE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CRX_PCTC_FK" FOREIGN KEY ("PRIMARY_CLIENT_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_TYPE_CODE" ("CLIENT_TYPE_CODE") ENABLE, 
	 CONSTRAINT "CRX_RELCD_FK" FOREIGN KEY ("CLIENT_RELATIONSHIP_CODE")
	  REFERENCES "THE"."CLIENT_RELATIONSHIP_CODE" ("CLIENT_RELATIONSHIP_CODE") ENABLE, 
	 CONSTRAINT "CRX_SCTC_FK" FOREIGN KEY ("SECONDARY_CLIENT_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_TYPE_CODE" ("CLIENT_TYPE_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_REORG_TYPE_CODE" 
   (	"CLIENT_REORG_TYPE_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CRTCD_PK" PRIMARY KEY ("CLIENT_REORG_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."MAILING_COUNTRY" 
   (	"COUNTRY_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(3), 
	 CONSTRAINT "CTRY_PK" PRIMARY KEY ("COUNTRY_NAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."MAILING_PROVINCE_STATE" 
   (	"COUNTRY_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PROVINCE_STATE_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PROVINCE_STATE_CODE" VARCHAR2(2), 
	 CONSTRAINT "PROV_PK" PRIMARY KEY ("PROVINCE_STATE_NAME", "COUNTRY_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PROV_CTRY_FK" FOREIGN KEY ("COUNTRY_NAME")
	  REFERENCES "THE"."MAILING_COUNTRY" ("COUNTRY_NAME") ENABLE
   ) ;

  CREATE TABLE "THE"."MAILING_CITY" 
   (	"COUNTRY_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PROVINCE_STATE_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"CITY_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "CTY_PK" PRIMARY KEY ("CITY_NAME", "PROVINCE_STATE_NAME", "COUNTRY_NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CTY_PROV_FK" FOREIGN KEY ("PROVINCE_STATE_NAME", "COUNTRY_NAME")
	  REFERENCES "THE"."MAILING_PROVINCE_STATE" ("PROVINCE_STATE_NAME", "COUNTRY_NAME") ENABLE
   ) ;

  CREATE TABLE "THE"."CLIENT_REORG_STATUS_CODE" 
   (	"CLIENT_REORG_STATUS_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CRSCD_PK" PRIMARY KEY ("CLIENT_REORG_STATUS_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."BUSINESS_CONTACT_CODE" 
   (	"BUSINESS_CONTACT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "BCC_PK" PRIMARY KEY ("BUSINESS_CONTACT_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."CLI_LOCN_AUDIT" 
   (	"CLIENT_LOCATION_AUDIT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"CLIENT_AUDIT_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"CLIENT_LOCN_NAME" VARCHAR2(40), 
	"HDBS_COMPANY_CODE" VARCHAR2(5), 
	"ADDRESS_1" VARCHAR2(40) NOT NULL ENABLE, 
	"ADDRESS_2" VARCHAR2(40), 
	"ADDRESS_3" VARCHAR2(40), 
	"CITY" VARCHAR2(30) NOT NULL ENABLE, 
	"PROVINCE" VARCHAR2(50), 
	"POSTAL_CODE" VARCHAR2(10), 
	"COUNTRY" VARCHAR2(50) NOT NULL ENABLE, 
	"BUSINESS_PHONE" VARCHAR2(10), 
	"HOME_PHONE" VARCHAR2(10), 
	"CELL_PHONE" VARCHAR2(10), 
	"FAX_NUMBER" VARCHAR2(10), 
	"EMAIL_ADDRESS" VARCHAR2(128), 
	"LOCN_EXPIRED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"RETURNED_MAIL_DATE" DATE, 
	"TRUST_LOCATION_IND" VARCHAR2(1), 
	"CLI_LOCN_COMMENT" VARCHAR2(4000), 
	"CLIENT_UPDATE_ACTION_CODE" VARCHAR2(4), 
	"CLIENT_UPDATE_REASON_CODE" VARCHAR2(4), 
	"CLIENT_TYPE_CODE" VARCHAR2(1), 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	"ADD_TIMESTAMP" DATE NOT NULL ENABLE, 
	"ADD_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ADD_ORG_UNIT" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "CLA_PK" PRIMARY KEY ("CLIENT_LOCATION_AUDIT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CLA_CAUDC_FK" FOREIGN KEY ("CLIENT_AUDIT_CODE")
	  REFERENCES "THE"."CLIENT_AUDIT_CODE" ("CLIENT_AUDIT_CODE") ENABLE, 
	 CONSTRAINT "CLA_OU_IS_CREATED_BY_FK" FOREIGN KEY ("ADD_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "CLA_OU_FK" FOREIGN KEY ("UPDATE_ORG_UNIT")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "CLA_CL_FK" FOREIGN KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "CLA_CARX_FK" FOREIGN KEY ("CLIENT_UPDATE_ACTION_CODE", "CLIENT_UPDATE_REASON_CODE", "CLIENT_TYPE_CODE")
	  REFERENCES "THE"."CLIENT_ACTION_REASON_XREF" ("CLIENT_UPDATE_ACTION_CODE", "CLIENT_UPDATE_REASON_CODE", "CLIENT_TYPE_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."MAX_CLIENT_NMBR" 
   (	"DUMMY_ACCESS_KEY" VARCHAR2(1) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE
   ) ;

   CREATE SEQUENCE  "THE"."CLIENT_LOCATION_AUDIT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1278953 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE TABLE "THE"."POLLEN_CONTAMINATION_MTHD_CODE" 
   (	"POLLEN_CONTAMINATION_MTHD_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PCMC_PK" PRIMARY KEY ("POLLEN_CONTAMINATION_MTHD_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."SEEDLOT_STATUS_CODE" 
   (	"SEEDLOT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SEEDLOT_STATUS_CODE_PK" ON "THE"."SEEDLOT_STATUS_CODE" ("SEEDLOT_STATUS_CODE") 
  ;
ALTER TABLE "THE"."SEEDLOT_STATUS_CODE" ADD CONSTRAINT "SEEDLOT_STATUS_CODE_PK" PRIMARY KEY ("SEEDLOT_STATUS_CODE")
  USING INDEX "THE"."SEEDLOT_STATUS_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."GENETIC_CLASS_CODE" 
   (	"GENETIC_CLASS_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."GENETIC_CLASS_CODE_PK" ON "THE"."GENETIC_CLASS_CODE" ("GENETIC_CLASS_CODE") 
  ;
ALTER TABLE "THE"."GENETIC_CLASS_CODE" ADD CONSTRAINT "GENETIC_CLASS_CODE_PK" PRIMARY KEY ("GENETIC_CLASS_CODE")
  USING INDEX "THE"."GENETIC_CLASS_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."SEED_PLAN_ZONE_CODE" 
   (	"SEED_PLAN_ZONE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SEED_PLAN_ZONE_CODE_PK" ON "THE"."SEED_PLAN_ZONE_CODE" ("SEED_PLAN_ZONE_CODE") 
  ;
ALTER TABLE "THE"."SEED_PLAN_ZONE_CODE" ADD CONSTRAINT "SEED_PLAN_ZONE_CODE_PK" PRIMARY KEY ("SEED_PLAN_ZONE_CODE")
  USING INDEX "THE"."SEED_PLAN_ZONE_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."SEED_COAST_AREA_CODE" 
   (	"SEED_COAST_AREA_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SEED_COAST_AREA_CODE_PK" ON "THE"."SEED_COAST_AREA_CODE" ("SEED_COAST_AREA_CODE") 
  ;
ALTER TABLE "THE"."SEED_COAST_AREA_CODE" ADD CONSTRAINT "SEED_COAST_AREA_CODE_PK" PRIMARY KEY ("SEED_COAST_AREA_CODE")
  USING INDEX "THE"."SEED_COAST_AREA_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."SEED_PLAN_UNIT" 
   (	"SEED_PLAN_UNIT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PRIMARY_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"SEED_PLAN_ZONE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ELEVATION_BAND" VARCHAR2(10) NOT NULL ENABLE, 
	"ELEVATION_MAX" NUMBER(5,0) NOT NULL ENABLE, 
	"ELEVATION_MIN" NUMBER(5,0) NOT NULL ENABLE, 
	"CREATE_DATE" DATE, 
	"LATITUDE_BAND" VARCHAR2(5), 
	"LATITUDE_DEGREES_MIN" NUMBER(2,0), 
	"LATITUDE_MINUTES_MIN" NUMBER(2,0), 
	"LATITUDE_DEGREES_MAX" NUMBER(2,0), 
	"LATITUDE_MINUTES_MAX" NUMBER(2,0), 
	"PROGRAM_RANK" NUMBER(3,0), 
	"TOTAL_SEEDLING_REQUIREMENTS" NUMBER(5,0), 
	"UPDATE_DATE" DATE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SPU_PK" ON "THE"."SEED_PLAN_UNIT" ("SEED_PLAN_UNIT_ID") 
  ;
ALTER TABLE "THE"."SEED_PLAN_UNIT" ADD CONSTRAINT "SPU_PK" PRIMARY KEY ("SEED_PLAN_UNIT_ID")
  USING INDEX "THE"."SPU_PK"  ENABLE;

  CREATE TABLE "THE"."COLLECTION_LATITUDE_CODE" 
   (	"COLLECTION_LATITUDE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."COLLECTION_LATITUDE_CODE_PK" ON "THE"."COLLECTION_LATITUDE_CODE" ("COLLECTION_LATITUDE_CODE") 
  ;
ALTER TABLE "THE"."COLLECTION_LATITUDE_CODE" ADD CONSTRAINT "COLLECTION_LATITUDE_CODE_PK" PRIMARY KEY ("COLLECTION_LATITUDE_CODE")
  USING INDEX "THE"."COLLECTION_LATITUDE_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."GENETIC_WORTH_CODE" 
   (	"GENETIC_WORTH_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."GENETIC_WORTH_CODE_PK" ON "THE"."GENETIC_WORTH_CODE" ("GENETIC_WORTH_CODE") 
  ;
ALTER TABLE "THE"."GENETIC_WORTH_CODE" ADD CONSTRAINT "GENETIC_WORTH_CODE_PK" PRIMARY KEY ("GENETIC_WORTH_CODE")
  USING INDEX "THE"."GENETIC_WORTH_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."SUPERIOR_PROVENANCE" 
   (	"PROVENANCE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"PROVENANCE_DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"VEGETATION_CODE" VARCHAR2(8) NOT NULL ENABLE, 
	"COLLECTION_ELEVATION_MIN" NUMBER(5,0) NOT NULL ENABLE, 
	"COLLECTION_ELEVATION_MAX" NUMBER(5,0) NOT NULL ENABLE, 
	"COLLECTION_LATITUDE_DEGREES" NUMBER(2,0), 
	"COLLECTION_LATITUDE_MINUTES" NUMBER(2,0), 
	"COLLECTION_LONGITUDE_DEGREES" NUMBER(3,0), 
	"COLLECTION_LONGITUDE_MINUTES" NUMBER(2,0), 
	"ADDITIONAL_CRITERIA" VARCHAR2(500), 
	"GENETIC_WORTH_CODE" VARCHAR2(3), 
	"GENETIC_WORTH_RATING" NUMBER(2,0), 
	"LIMIT_UP_ELEVATION" NUMBER(5,0), 
	"LIMIT_DOWN_ELEVATION" NUMBER(5,0), 
	"LIMIT_ELEVATION_MIN" NUMBER(5,0), 
	"LIMIT_ELEVATION_MAX" NUMBER(5,0), 
	"LIMIT_LATITUDE_MIN_DEGREES" NUMBER(2,0), 
	"LIMIT_LATITUDE_MIN_MINUTES" NUMBER(2,0), 
	"LIMIT_LATITUDE_MAX_DEGREES" NUMBER(2,0), 
	"LIMIT_LATITUDE_MAX_MINUTES" NUMBER(2,0), 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "SUPR_PK" PRIMARY KEY ("PROVENANCE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SUPR_VC_FK" FOREIGN KEY ("VEGETATION_CODE")
	  REFERENCES "THE"."VEGETATION_CODE" ("VEGETATION_CODE") ENABLE, 
	 CONSTRAINT "SUPR_GWC_FK" FOREIGN KEY ("GENETIC_WORTH_CODE")
	  REFERENCES "THE"."GENETIC_WORTH_CODE" ("GENETIC_WORTH_CODE") ENABLE
   ) ;

  CREATE TABLE "THE"."INTERM_FACILITY_CODE" 
   (	"INTERM_FACILITY_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."INTERM_FACILITY_CODE_PK" ON "THE"."INTERM_FACILITY_CODE" ("INTERM_FACILITY_CODE") 
  ;
ALTER TABLE "THE"."INTERM_FACILITY_CODE" ADD CONSTRAINT "INTERM_FACILITY_CODE_PK" PRIMARY KEY ("INTERM_FACILITY_CODE")
  USING INDEX "THE"."INTERM_FACILITY_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."GAMETIC_MTHD_CODE" 
   (	"GAMETIC_MTHD_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "GCMC_PK" PRIMARY KEY ("GAMETIC_MTHD_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."COLLECTION_LONGITUDE_CODE" 
   (	"COLLECTION_LONGITUDE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."COLLECTION_LONGITUDE_CODE_PK" ON "THE"."COLLECTION_LONGITUDE_CODE" ("COLLECTION_LONGITUDE_CODE") 
  ;
ALTER TABLE "THE"."COLLECTION_LONGITUDE_CODE" ADD CONSTRAINT "COLLECTION_LONGITUDE_CODE_PK" PRIMARY KEY ("COLLECTION_LONGITUDE_CODE")
  USING INDEX "THE"."COLLECTION_LONGITUDE_CODE_PK"  ENABLE;

  CREATE TABLE "THE"."BEC_VERSION_CONTROL" 
   (	"BEC_VERSION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BEC_VERSION" NUMBER(5,2) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE, 
	 CONSTRAINT "BVC_BV_UK" UNIQUE ("BEC_VERSION")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BVC_PK" PRIMARY KEY ("BEC_VERSION_ID")
  USING INDEX  ENABLE
   ) ;

   CREATE SEQUENCE  "THE"."SAUD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 314438 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE TABLE "THE"."SEEDLOT" 
   (	"SEEDLOT_NUMBER" VARCHAR2(5) NOT NULL ENABLE, 
	"SEEDLOT_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"VEGETATION_CODE" VARCHAR2(8), 
	"GENETIC_CLASS_CODE" VARCHAR2(1), 
	"COLLECTION_SOURCE_CODE" VARCHAR2(2), 
	"SUPERIOR_PRVNC_IND" VARCHAR2(1), 
	"ORG_UNIT_NO" NUMBER(10,0), 
	"REGISTERED_SEED_IND" VARCHAR2(1), 
	"TO_BE_REGISTRD_IND" VARCHAR2(1), 
	"REGISTERED_DATE" DATE, 
	"FS721A_SIGNED_IND" VARCHAR2(1), 
	"BC_SOURCE_IND" VARCHAR2(1), 
	"NAD_DATUM_CODE" VARCHAR2(2), 
	"UTM_ZONE" NUMBER(5,0), 
	"UTM_EASTING" NUMBER(10,0), 
	"UTM_NORTHING" NUMBER(10,0), 
	"LONGITUDE_DEGREES" NUMBER(3,0), 
	"LONGITUDE_MINUTES" NUMBER(2,0), 
	"LONGITUDE_SECONDS" NUMBER(2,0), 
	"LONGITUDE_DEG_MIN" NUMBER(3,0), 
	"LONGITUDE_MIN_MIN" NUMBER(2,0), 
	"LONGITUDE_SEC_MIN" NUMBER(2,0), 
	"LONGITUDE_DEG_MAX" NUMBER(3,0), 
	"LONGITUDE_MIN_MAX" NUMBER(2,0), 
	"LONGITUDE_SEC_MAX" NUMBER(2,0), 
	"LATITUDE_DEGREES" NUMBER(2,0), 
	"LATITUDE_MINUTES" NUMBER(2,0), 
	"LATITUDE_SECONDS" NUMBER(2,0), 
	"LATITUDE_DEG_MIN" NUMBER(2,0), 
	"LATITUDE_MIN_MIN" NUMBER(2,0), 
	"LATITUDE_SEC_MIN" NUMBER(2,0), 
	"LATITUDE_DEG_MAX" NUMBER(2,0), 
	"LATITUDE_MIN_MAX" NUMBER(2,0), 
	"LATITUDE_SEC_MAX" NUMBER(2,0), 
	"SEED_COAST_AREA_CODE" VARCHAR2(3), 
	"ELEVATION" NUMBER(5,0), 
	"ELEVATION_MIN" NUMBER(5,0), 
	"ELEVATION_MAX" NUMBER(5,0), 
	"SEED_PLAN_UNIT_ID" NUMBER(10,0), 
	"ORCHARD_ID" VARCHAR2(3), 
	"SECONDARY_ORCHARD_ID" VARCHAR2(3), 
	"COLLECTION_LOCN_DESC" VARCHAR2(30), 
	"COLLECTION_CLI_NUMBER" VARCHAR2(8), 
	"COLLECTION_CLI_LOCN_CD" VARCHAR2(2), 
	"COLLECTION_START_DATE" DATE, 
	"COLLECTION_END_DATE" DATE, 
	"CONE_COLLECTION_METHOD_CODE" VARCHAR2(3), 
	"CONE_COLLECTION_METHOD2_CODE" VARCHAR2(3), 
	"COLLECTION_LAT_DEG" NUMBER(2,0), 
	"COLLECTION_LAT_MIN" NUMBER(2,0), 
	"COLLECTION_LAT_SEC" NUMBER(2,0), 
	"COLLECTION_LATITUDE_CODE" VARCHAR2(2), 
	"COLLECTION_LONG_DEG" NUMBER(3,0), 
	"COLLECTION_LONG_MIN" NUMBER(2,0), 
	"COLLECTION_LONG_SEC" NUMBER(2,0), 
	"COLLECTION_LONGITUDE_CODE" VARCHAR2(2), 
	"COLLECTION_ELEVATION" NUMBER(5,0), 
	"COLLECTION_ELEVATION_MIN" NUMBER(5,0), 
	"COLLECTION_ELEVATION_MAX" NUMBER(5,0), 
	"COLLECTION_AREA_RADIUS" NUMBER(5,1), 
	"COLLECTION_SEED_PLAN_ZONE_IND" VARCHAR2(1), 
	"COLLECTION_BGC_IND" VARCHAR2(1), 
	"NO_OF_CONTAINERS" NUMBER(6,2), 
	"CLCTN_VOLUME" NUMBER(6,2), 
	"VOL_PER_CONTAINER" NUMBER(6,2), 
	"NMBR_TREES_FROM_CODE" VARCHAR2(1), 
	"EFFECTIVE_POP_SIZE" NUMBER(5,1), 
	"ORIGINAL_SEED_QTY" NUMBER(10,0), 
	"INTERM_STRG_CLIENT_NUMBER" VARCHAR2(8), 
	"INTERM_STRG_CLIENT_LOCN" VARCHAR2(2), 
	"INTERM_STRG_ST_DATE" DATE, 
	"INTERM_STRG_END_DATE" DATE, 
	"INTERM_FACILITY_CODE" VARCHAR2(3), 
	"INTERM_STRG_LOCN" VARCHAR2(55), 
	"INTERM_STRG_CMT" VARCHAR2(125), 
	"EXTRACTION_ST_DATE" DATE, 
	"EXTRACTION_END_DATE" DATE, 
	"EXTRACTION_VOLUME" NUMBER(6,2), 
	"EXTRCT_CLI_NUMBER" VARCHAR2(8), 
	"EXTRCT_CLI_LOCN_CD" VARCHAR2(2), 
	"EXTRACTION_COMMENT" VARCHAR2(125), 
	"STORED_CLI_NUMBER" VARCHAR2(8), 
	"STORED_CLI_LOCN_CD" VARCHAR2(2), 
	"LNGTERM_STRG_ST_DATE" DATE, 
	"HISTORICAL_TSR_DATE" DATE, 
	"OWNERSHIP_COMMENT" VARCHAR2(4000), 
	"CONE_SEED_DESC" VARCHAR2(250), 
	"SEEDLOT_COMMENT" VARCHAR2(2000), 
	"TEMPORARY_STORAGE_START_DATE" DATE, 
	"TEMPORARY_STORAGE_END_DATE" DATE, 
	"COLLECTION_STANDARD_MET_IND" VARCHAR2(1), 
	"APPLICANT_EMAIL_ADDRESS" VARCHAR2(100), 
	"BIOTECH_PROCESSES_IND" VARCHAR2(1), 
	"POLLEN_CONTAMINATION_IND" VARCHAR2(1), 
	"POLLEN_CONTAMINATION_PCT" NUMBER(3,0), 
	"CONTROLLED_CROSS_IND" VARCHAR2(1), 
	"ORCHARD_COMMENT" VARCHAR2(2000), 
	"TOTAL_PARENT_TREES" NUMBER(5,0), 
	"SMP_PARENTS_OUTSIDE" NUMBER(5,0), 
	"SMP_MEAN_BV_GROWTH" NUMBER(4,1), 
	"SMP_SUCCESS_PCT" NUMBER(3,0), 
	"CONTAMINANT_POLLEN_BV" NUMBER(4,1), 
	"ORCHARD_CONTAMINATION_PCT" NUMBER(3,0), 
	"COANCESTRY" NUMBER(20,10), 
	"PROVENANCE_ID" NUMBER(5,0), 
	"SEED_PLAN_ZONE_CODE" VARCHAR2(3), 
	"POLLEN_CONTAMINATION_MTHD_CODE" VARCHAR2(4), 
	"APPLICANT_CLIENT_NUMBER" VARCHAR2(8), 
	"APPLICANT_CLIENT_LOCN" VARCHAR2(2), 
	"SEED_STORE_CLIENT_NUMBER" VARCHAR2(8), 
	"SEED_STORE_CLIENT_LOCN" VARCHAR2(2), 
	"SEEDLOT_SOURCE_CODE" VARCHAR2(3), 
	"FEMALE_GAMETIC_MTHD_CODE" VARCHAR2(4), 
	"MALE_GAMETIC_MTHD_CODE" VARCHAR2(4), 
	"BGC_ZONE_CODE" VARCHAR2(4), 
	"BGC_SUBZONE_CODE" VARCHAR2(3), 
	"VARIANT" VARCHAR2(1), 
	"BEC_VERSION_ID" NUMBER(10,0), 
	"PRICE_PER_KG" NUMBER(7,2), 
	"PRICE_COMMENT" VARCHAR2(2000), 
	"APPROVED_USERID" VARCHAR2(30), 
	"APPROVED_TIMESTAMP" DATE, 
	"DECLARED_USERID" VARCHAR2(30), 
	"DECLARED_TIMESTAMP" DATE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SEEDLOT_PK" PRIMARY KEY ("SEEDLOT_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SPR_SEE_CSC2_FK" FOREIGN KEY ("COLLECTION_SOURCE_CODE")
	  REFERENCES "THE"."COLLECTION_SOURCE_CODE" ("COLLECTION_SOURCE_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_CL2_FK" FOREIGN KEY ("APPLICANT_CLIENT_NUMBER", "APPLICANT_CLIENT_LOCN")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_ORC2_FK" FOREIGN KEY ("SECONDARY_ORCHARD_ID")
	  REFERENCES "THE"."ORCHARD" ("ORCHARD_ID") ENABLE, 
	 CONSTRAINT "SPR_SEE_SSCD_FK" FOREIGN KEY ("SEEDLOT_SOURCE_CODE")
	  REFERENCES "THE"."SEEDLOT_SOURCE_CODE" ("SEEDLOT_SOURCE_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_PCMC_FK" FOREIGN KEY ("POLLEN_CONTAMINATION_MTHD_CODE")
	  REFERENCES "THE"."POLLEN_CONTAMINATION_MTHD_CODE" ("POLLEN_CONTAMINATION_MTHD_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_SSC3_FK" FOREIGN KEY ("SEEDLOT_STATUS_CODE")
	  REFERENCES "THE"."SEEDLOT_STATUS_CODE" ("SEEDLOT_STATUS_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_CLC_FK" FOREIGN KEY ("COLLECTION_LATITUDE_CODE")
	  REFERENCES "THE"."COLLECTION_LATITUDE_CODE" ("COLLECTION_LATITUDE_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_SCAC_FK" FOREIGN KEY ("SEED_COAST_AREA_CODE")
	  REFERENCES "THE"."SEED_COAST_AREA_CODE" ("SEED_COAST_AREA_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_SPZC_FK" FOREIGN KEY ("SEED_PLAN_ZONE_CODE")
	  REFERENCES "THE"."SEED_PLAN_ZONE_CODE" ("SEED_PLAN_ZONE_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_CCMC2_FK" FOREIGN KEY ("CONE_COLLECTION_METHOD2_CODE")
	  REFERENCES "THE"."CONE_COLLECTION_METHOD_CODE" ("CONE_COLLECTION_METHOD_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_SPU_FK" FOREIGN KEY ("SEED_PLAN_UNIT_ID")
	  REFERENCES "THE"."SEED_PLAN_UNIT" ("SEED_PLAN_UNIT_ID") ENABLE, 
	 CONSTRAINT "SPR_SEE_GMC1_FK" FOREIGN KEY ("FEMALE_GAMETIC_MTHD_CODE")
	  REFERENCES "THE"."GAMETIC_MTHD_CODE" ("GAMETIC_MTHD_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_CL3_FK" FOREIGN KEY ("INTERM_STRG_CLIENT_NUMBER", "INTERM_STRG_CLIENT_LOCN")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_SUPR_FK" FOREIGN KEY ("PROVENANCE_ID")
	  REFERENCES "THE"."SUPERIOR_PROVENANCE" ("PROVENANCE_ID") ENABLE, 
	 CONSTRAINT "SPR_SEE_NDC_FK" FOREIGN KEY ("NAD_DATUM_CODE")
	  REFERENCES "THE"."NAD_DATUM_CODE" ("NAD_DATUM_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_NTFC_FK" FOREIGN KEY ("NMBR_TREES_FROM_CODE")
	  REFERENCES "THE"."NMBR_TREES_FROM_CODE" ("NMBR_TREES_FROM_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_VC_FK" FOREIGN KEY ("VEGETATION_CODE")
	  REFERENCES "THE"."VEGETATION_CODE" ("VEGETATION_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_CLC1_FK" FOREIGN KEY ("COLLECTION_LONGITUDE_CODE")
	  REFERENCES "THE"."COLLECTION_LONGITUDE_CODE" ("COLLECTION_LONGITUDE_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_CL1_FK" FOREIGN KEY ("SEED_STORE_CLIENT_NUMBER", "SEED_STORE_CLIENT_LOCN")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_CCMC_FK" FOREIGN KEY ("CONE_COLLECTION_METHOD_CODE")
	  REFERENCES "THE"."CONE_COLLECTION_METHOD_CODE" ("CONE_COLLECTION_METHOD_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_GMC2_FK" FOREIGN KEY ("MALE_GAMETIC_MTHD_CODE")
	  REFERENCES "THE"."GAMETIC_MTHD_CODE" ("GAMETIC_MTHD_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_GCC_FK" FOREIGN KEY ("GENETIC_CLASS_CODE")
	  REFERENCES "THE"."GENETIC_CLASS_CODE" ("GENETIC_CLASS_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_IFC_FK" FOREIGN KEY ("INTERM_FACILITY_CODE")
	  REFERENCES "THE"."INTERM_FACILITY_CODE" ("INTERM_FACILITY_CODE") ENABLE, 
	 CONSTRAINT "SPR_SEE_ORC_FK" FOREIGN KEY ("ORCHARD_ID")
	  REFERENCES "THE"."ORCHARD" ("ORCHARD_ID") ENABLE, 
	 CONSTRAINT "SPR_SEE_OU1_FK" FOREIGN KEY ("ORG_UNIT_NO")
	  REFERENCES "THE"."ORG_UNIT" ("ORG_UNIT_NO") ENABLE, 
	 CONSTRAINT "SPR_SEE_BVC_FK" FOREIGN KEY ("BEC_VERSION_ID")
	  REFERENCES "THE"."BEC_VERSION_CONTROL" ("BEC_VERSION_ID") ENABLE
   ) ;
