
   CREATE SEQUENCE  "THE"."SGWA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 8830 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE TABLE "THE"."SEEDLOT_GENETIC_WORTH" 
   (	"SEEDLOT_NUMBER" VARCHAR2(5) NOT NULL ENABLE, 
	"GENETIC_WORTH_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"GENETIC_WORTH_RTNG" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SEEDLOT_GENETIC_WORTH_PK" ON "THE"."SEEDLOT_GENETIC_WORTH" ("SEEDLOT_NUMBER", "GENETIC_WORTH_CODE") 
  ;
ALTER TABLE "THE"."SEEDLOT_GENETIC_WORTH" ADD CONSTRAINT "SEEDLOT_GENETIC_WORTH_PK" PRIMARY KEY ("SEEDLOT_NUMBER", "GENETIC_WORTH_CODE")
  USING INDEX "THE"."SEEDLOT_GENETIC_WORTH_PK"  ENABLE;
