
   CREATE SEQUENCE  "THE"."SOQA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 102582 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE TABLE "THE"."SEEDLOT_OWNER_QUANTITY" 
   (	"SEEDLOT_NUMBER" VARCHAR2(5) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"ORIGINAL_PCT_OWNED" NUMBER(4,1) NOT NULL ENABLE, 
	"ORIGINAL_PCT_RSRVD" NUMBER(4,1) NOT NULL ENABLE, 
	"ORIGINAL_PCT_SRPLS" NUMBER(4,1) NOT NULL ENABLE, 
	"QTY_RESERVED" NUMBER(10,0) NOT NULL ENABLE, 
	"QTY_RSRVD_CMTD_PLN" NUMBER(10,0) NOT NULL ENABLE, 
	"QTY_RSRVD_CMTD_APR" NUMBER(10,0) NOT NULL ENABLE, 
	"QTY_SURPLUS" NUMBER(10,0) NOT NULL ENABLE, 
	"QTY_SRPLS_CMTD_PLN" NUMBER(10,0) NOT NULL ENABLE, 
	"QTY_SRPLS_CMTD_APR" NUMBER(10,0) NOT NULL ENABLE, 
	"AUTHORIZATION_CODE" VARCHAR2(3), 
	"METHOD_OF_PAYMENT_CODE" VARCHAR2(3), 
	"SPAR_FUND_SRCE_CODE" VARCHAR2(3), 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."SEEDLOT_OWNER_QUANTITY_PK" ON "THE"."SEEDLOT_OWNER_QUANTITY" ("SEEDLOT_NUMBER", "CLIENT_NUMBER", "CLIENT_LOCN_CODE") 
  ;
ALTER TABLE "THE"."SEEDLOT_OWNER_QUANTITY" ADD CONSTRAINT "SEEDLOT_OWNER_QUANTITY_PK" PRIMARY KEY ("SEEDLOT_NUMBER", "CLIENT_NUMBER", "CLIENT_LOCN_CODE")
  USING INDEX "THE"."SEEDLOT_OWNER_QUANTITY_PK"  ENABLE;
