
  CREATE TABLE "THE"."GENETIC_TYPE_CODE" 
   (	"GENETIC_TYPE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "GTCD_PK" PRIMARY KEY ("GENETIC_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."SEEDLOT_PARENT_TREE_GEN_QLTY" 
   (	"SEEDLOT_NUMBER" VARCHAR2(5) NOT NULL ENABLE, 
	"PARENT_TREE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"GENETIC_TYPE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"GENETIC_WORTH_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"SEED_PLAN_UNIT_ID" NUMBER(10,0), 
	"GENETIC_QUALITY_VALUE" NUMBER(4,1) NOT NULL ENABLE, 
	"ESTIMATED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"UNTESTED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SPTGQ_PK" PRIMARY KEY ("PARENT_TREE_ID", "SEEDLOT_NUMBER", "GENETIC_TYPE_CODE", "GENETIC_WORTH_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SPTGQ_GTCD_FK" FOREIGN KEY ("GENETIC_TYPE_CODE")
	  REFERENCES "THE"."GENETIC_TYPE_CODE" ("GENETIC_TYPE_CODE") ENABLE, 
	 CONSTRAINT "SPTGQ_GWC_FK" FOREIGN KEY ("GENETIC_WORTH_CODE")
	  REFERENCES "THE"."GENETIC_WORTH_CODE" ("GENETIC_WORTH_CODE") ENABLE, 
	 CONSTRAINT "SPTGQ_ST2_FK" FOREIGN KEY ("SEED_PLAN_UNIT_ID")
	  REFERENCES "THE"."SEED_PLAN_UNIT" ("SEED_PLAN_UNIT_ID") ENABLE, 
	 CONSTRAINT "SPTGQ_SPT_FK" FOREIGN KEY ("SEEDLOT_NUMBER", "PARENT_TREE_ID")
	  REFERENCES "THE"."SEEDLOT_PARENT_TREE" ("SEEDLOT_NUMBER", "PARENT_TREE_ID") ENABLE
   ) ;
