
  CREATE TABLE "THE"."SMP_MIX_GEN_QLTY" 
   (	"SEEDLOT_NUMBER" VARCHAR2(5) NOT NULL ENABLE, 
	"PARENT_TREE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"GENETIC_TYPE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"GENETIC_WORTH_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"GENETIC_QUALITY_VALUE" NUMBER(4,1) NOT NULL ENABLE, 
	"ESTIMATED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SMGQ_PK" PRIMARY KEY ("PARENT_TREE_ID", "SEEDLOT_NUMBER", "GENETIC_TYPE_CODE", "GENETIC_WORTH_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SMGQ_GTCD_FK" FOREIGN KEY ("GENETIC_TYPE_CODE")
	  REFERENCES "THE"."GENETIC_TYPE_CODE" ("GENETIC_TYPE_CODE") ENABLE, 
	 CONSTRAINT "SMGQ_GWC_FK" FOREIGN KEY ("GENETIC_WORTH_CODE")
	  REFERENCES "THE"."GENETIC_WORTH_CODE" ("GENETIC_WORTH_CODE") ENABLE, 
	 CONSTRAINT "SMGQ_SMPM_FK" FOREIGN KEY ("SEEDLOT_NUMBER", "PARENT_TREE_ID")
	  REFERENCES "THE"."SMP_MIX" ("SEEDLOT_NUMBER", "PARENT_TREE_ID") ENABLE
   ) ;
