
  CREATE TABLE "THE"."SEED_PLAN_ZONE" 
   (	"SEED_PLAN_ZONE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"GENETIC_CLASS_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"SEED_PLAN_ZONE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"VEGETATION_CODE" VARCHAR2(8), 
	 CONSTRAINT "SPZS_PK" PRIMARY KEY ("SEED_PLAN_ZONE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SPZS_SPZC1_FK" FOREIGN KEY ("SEED_PLAN_ZONE_CODE")
	  REFERENCES "THE"."SEED_PLAN_ZONE_CODE" ("SEED_PLAN_ZONE_CODE") ENABLE, 
	 CONSTRAINT "SPZS_VC_FK" FOREIGN KEY ("VEGETATION_CODE")
	  REFERENCES "THE"."VEGETATION_CODE" ("VEGETATION_CODE") ENABLE, 
	 CONSTRAINT "SPZS_GCC_FK" FOREIGN KEY ("GENETIC_CLASS_CODE")
	  REFERENCES "THE"."GENETIC_CLASS_CODE" ("GENETIC_CLASS_CODE") ENABLE
   ) ;
