
  CREATE TABLE "THE"."BREEDING_SELECTION_TYPE_CODE" 
   (	"BREEDING_SELECTION_TYPE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "BSTCD_PK" PRIMARY KEY ("BREEDING_SELECTION_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."NATURAL_SELECTION_TYPE_CODE" 
   (	"NATURAL_SELECTION_TYPE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "NSTCD_PK" PRIMARY KEY ("NATURAL_SELECTION_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."PARENT_TREE_REG_STATUS_CODE" 
   (	"PARENT_TREE_REG_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PTRSC_PK" PRIMARY KEY ("PARENT_TREE_REG_STATUS_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."PARENT_TREE" 
   (	"PARENT_TREE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_TREE_NUMBER" VARCHAR2(5) NOT NULL ENABLE, 
	"VEGETATION_CODE" VARCHAR2(8) NOT NULL ENABLE, 
	"PARENT_TREE_REG_STATUS_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"LOCAL_NUMBER" VARCHAR2(20), 
	"ACTIVE_IND" VARCHAR2(1), 
	"TESTED_IND" VARCHAR2(1), 
	"BREEDING_PROGRAM_IND" VARCHAR2(1), 
	"SELECTION_DATE" DATE, 
	"BC_SOURCE_IND" VARCHAR2(1), 
	"CLIENT_NUMBER" VARCHAR2(8), 
	"CLIENT_LOCN_CODE" VARCHAR2(2), 
	"NATURAL_SELECTION_TYPE_CODE" VARCHAR2(3), 
	"GEOGRAPHIC_LOCATION" VARCHAR2(30), 
	"LATITUDE_DEGREES" NUMBER(2,0), 
	"LATITUDE_MINUTES" NUMBER(2,0), 
	"LATITUDE_SECONDS" NUMBER(2,0), 
	"LONGITUDE_DEGREES" NUMBER(3,0), 
	"LONGITUDE_MINUTES" NUMBER(2,0), 
	"LONGITUDE_SECONDS" NUMBER(2,0), 
	"SEED_PLAN_ZONE_CODE" VARCHAR2(3), 
	"ELEVATION" NUMBER(5,0), 
	"SELECTION_AGE" NUMBER(3,0), 
	"BGC_ZONE_CODE" VARCHAR2(4), 
	"BGC_SUBZONE_CODE" VARCHAR2(3), 
	"BGC_VARIANT" VARCHAR2(1), 
	"BREEDING_SELECTION_TYPE_CODE" VARCHAR2(3), 
	"FEMALE_PARENT_PARENT_TREE_ID" NUMBER(10,0), 
	"MALE_PARENT_PARENT_TREE_ID" NUMBER(10,0), 
	"PARENT_TREE_COMMENT" VARCHAR2(2000), 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "PT_PK" PRIMARY KEY ("PARENT_TREE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PT_UK" UNIQUE ("PARENT_TREE_NUMBER", "VEGETATION_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PT_VEGETATION_CODE_FK" FOREIGN KEY ("VEGETATION_CODE")
	  REFERENCES "THE"."VEGETATION_CODE" ("VEGETATION_CODE") ENABLE, 
	 CONSTRAINT "PT_BSTCD_FK" FOREIGN KEY ("BREEDING_SELECTION_TYPE_CODE")
	  REFERENCES "THE"."BREEDING_SELECTION_TYPE_CODE" ("BREEDING_SELECTION_TYPE_CODE") ENABLE, 
	 CONSTRAINT "PT_SEED_PLAN_ZONE_CODE_FK" FOREIGN KEY ("SEED_PLAN_ZONE_CODE")
	  REFERENCES "THE"."SEED_PLAN_ZONE_CODE" ("SEED_PLAN_ZONE_CODE") ENABLE, 
	 CONSTRAINT "PT_PTRSC_FK" FOREIGN KEY ("PARENT_TREE_REG_STATUS_CODE")
	  REFERENCES "THE"."PARENT_TREE_REG_STATUS_CODE" ("PARENT_TREE_REG_STATUS_CODE") ENABLE, 
	 CONSTRAINT "PT_NSTCD_FK" FOREIGN KEY ("NATURAL_SELECTION_TYPE_CODE")
	  REFERENCES "THE"."NATURAL_SELECTION_TYPE_CODE" ("NATURAL_SELECTION_TYPE_CODE") ENABLE, 
	 CONSTRAINT "PT_BZC_FK" FOREIGN KEY ("BGC_ZONE_CODE")
	  REFERENCES "THE"."BEC_ZONE_CODE" ("BEC_ZONE_CODE") ENABLE, 
	 CONSTRAINT "PT_CL1_FK" FOREIGN KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "PT_PT_MALE_PARENT_FK" FOREIGN KEY ("MALE_PARENT_PARENT_TREE_ID")
	  REFERENCES "THE"."PARENT_TREE" ("PARENT_TREE_ID") ENABLE, 
	 CONSTRAINT "PT_PT_FEMALE_PARENT_FK" FOREIGN KEY ("FEMALE_PARENT_PARENT_TREE_ID")
	  REFERENCES "THE"."PARENT_TREE" ("PARENT_TREE_ID") ENABLE
   ) ;

  CREATE TABLE "THE"."SMP_MIX" 
   (	"SEEDLOT_NUMBER" VARCHAR2(5) NOT NULL ENABLE, 
	"PARENT_TREE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AMOUNT_OF_MATERIAL" NUMBER(6,0) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SMPM_PK" PRIMARY KEY ("SEEDLOT_NUMBER", "PARENT_TREE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SMPM_PT_FK" FOREIGN KEY ("PARENT_TREE_ID")
	  REFERENCES "THE"."PARENT_TREE" ("PARENT_TREE_ID") ENABLE, 
	 CONSTRAINT "SMPM_SEE_FK" FOREIGN KEY ("SEEDLOT_NUMBER")
	  REFERENCES "THE"."SEEDLOT" ("SEEDLOT_NUMBER") ENABLE
   ) ;

  CREATE TABLE "THE"."GENETIC_TYPE_CODE" 
   (	"GENETIC_TYPE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	 CONSTRAINT "GTCD_PK" PRIMARY KEY ("GENETIC_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "THE"."SMP_MIX_GEN_QLTY" 
   (	"SEEDLOT_NUMBER" VARCHAR2(5) NOT NULL ENABLE, 
	"PARENT_TREE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"GENETIC_TYPE_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"GENETIC_WORTH_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"GENETIC_QUALITY_VALUE" NUMBER(4,1) NOT NULL ENABLE, 
	"ESTIMATED_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "SMGQ_PK" PRIMARY KEY ("PARENT_TREE_ID", "SEEDLOT_NUMBER", "GENETIC_TYPE_CODE", "GENETIC_WORTH_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SMGQ_GTCD_FK" FOREIGN KEY ("GENETIC_TYPE_CODE")
	  REFERENCES "THE"."GENETIC_TYPE_CODE" ("GENETIC_TYPE_CODE") ENABLE, 
	 CONSTRAINT "SMGQ_GWC_FK" FOREIGN KEY ("GENETIC_WORTH_CODE")
	  REFERENCES "THE"."GENETIC_WORTH_CODE" ("GENETIC_WORTH_CODE") ENABLE, 
	 CONSTRAINT "SMGQ_SMPM_FK" FOREIGN KEY ("SEEDLOT_NUMBER", "PARENT_TREE_ID")
	  REFERENCES "THE"."SMP_MIX" ("SEEDLOT_NUMBER", "PARENT_TREE_ID") ENABLE
   ) ;
