apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: nr-spar
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: ORACLE_HOST
    description: Oracle database host
    value: nrcdb03.bcgov
    required: true
  - name: ORACLE_SERVICE
    description: Oracle service name
    value: dbq01.nrs.bcgov
  - name: ORACLE_SYNC_PASSWORD
    description: Oracle database password for Sync
    required: true
  - name: ORACLE_SYNC_USER
    description: Oracle database username for Sync
    value: proxy_fsa_spar_sync_user
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-sync
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      oracle-host: ${ORACLE_HOST}
      oracle-service: ${ORACLE_SERVICE}
      oracle-sync-password: ${ORACLE_SYNC_PASSWORD}
      oracle-sync-user: ${ORACLE_SYNC_USER}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-spar-backend-network-security-policy
    spec:
      policyTypes:
        - Ingress
