#!/bin/sh

sqlplus sys/$ORACLE_PASSWORD@localhost:1521/$ORACLE_DATABASE as sysdba <<EOF
GRANT CONNECT TO $APP_USER;
GRANT RESOURCE TO $APP_USER;
GRANT CREATE SESSION TO $APP_USER;
GRANT CREATE ANY TABLE TO $APP_USER;
GRANT CREATE ANY INDEX TO $APP_USER;
GRANT ALTER ANY TABLE TO $APP_USER;
GRANT CREATE ANY VIEW TO $APP_USER;
GRANT ALL PRIVILEGES TO $APP_USER;
EXIT;
EOF