name: ETL PROD

on:
  schedule: [cron: "30 */2 * * *"] # Every other hour on the hour
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  etl-prod:
    name: ETL (PROD)
    environment: prod
    runs-on: ubuntu-24.04
    steps:
      - timeout-minutes: 10
        uses: bcgov/action-oc-runner@v1.0.0
        with:
          cronjob: ${{ github.event.repository.name }}-${{ github.event.number }}-sync
          cronjob_tail: -1
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
