name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '.github/graphics/**'
      - '!.github/workflows/**'

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  init:
    name: Initialize
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-24.04
    steps:
        # Get PR number for squash merges to main
      - id: pr
        uses: bcgov/action-get-pr@v0.0.1

  deploys-test:
    name: TEST Deploys (${{ needs.init.outputs.pr }})
    needs: [init]
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml
    with:
      environment: test
      postgres-host: nr-spar-test-database
      tag: ${{ needs.init.outputs.pr }}
      target: test
      test-mode: false

  deploys-prod:
    name: PROD Deploys (${{ needs.init.outputs.pr }})
    needs: [init, deploys-test]
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml
    with:
      environment: prod
      postgres-host: nr-spar-prod-database
      tag: ${{ needs.init.outputs.pr }}
      target: prod
      test-mode: true

  promote:
    name: Promote Images
    needs: [init, deploys-prod]
    runs-on: ubuntu-24.04
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/sync
          target: ${{ needs.init.outputs.pr }}
          tags: prod
