name: PR

on:
  pull_request:

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          package: sync
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('sync/')

  # Will address this when move the actual sync job to this repository.
  # deploys:
  #   name: Deploys (${{ github.event.number }})
  #   needs: [builds]
  #   secrets: inherit
  #   uses: ./.github/workflows/.deploy.yml

  results:
    name: PR Results
    if: always()
    # Include all needs that could have failures!
    # remove deploys until got the actual sync job running in this repo
    # [builds, deploys]
    needs: [builds]
    runs-on: ubuntu-24.04
    steps:
      - run: |
          # View results
          echo "needs.*.result: ${{ toJson(needs.*.result) }}"

      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: |
          # Job failure found
          echo "At least one job has failed"
          exit 1
