name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate PR
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@v0.7.0
    with:
      markdown_links: |
        - This application will be run as a [GitHub Action](https://github.com/${{ github.repository }}/actions)

  results:
    name: Validate Results
    if: always() && (!failure()) && (!cancelled())
    needs: [validate]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Success!"
